const Footer = () => {
  return (
    <div className="footer">
      {/* Support for skyexchange */}
      <div className="support-wrap extend-support">
        <div className="extend-wrap">
          <div className="extend-btn">
            <img
              src="/images/transparent.gif"
              title="customer"
              className="support-customer"
            />
            <a href="https://wa.link/skyexchcs" target="_blank">
              Customer support1
            </a>
            <a
              href="https://wa.link/skyexchcs"
              target="_blank"
              className="split-line"
            >
              support2
            </a>
          </div>
          <div className="extend-btn">
            <img
              src="/images/transparent.gif"
              title="WhatsApp"
              className="support-whatsapp"
            />
            <a href="https://linktr.ee/SKY_EXCH" target="_blank">
              WhatsApp 3
            </a>
            <a
              href="https://linktr.ee/SKY_EXCH"
              target="_blank"
              className="split-line"
            >
              WhatsApp 4
            </a>
          </div>
        </div>
        <div className="extend-btn" />
        <div className="extend-wrap">
          <div className="support-social">
            <img
              src="/images/transparent.gif"
              title="Skype"
              className="support-skype"
            />
            <a href="skype:skyexchangeofficial?chat" target="_blank">
              skyexchangeofficial
            </a>
          </div>
          <div className="support-social">
            <img
              src="/images/transparent.gif"
              title="Email"
              className="support-mail"
            />
            <a href="mailto:info@skyexchange.com" target="_blank">
              info@skyexchange.com
            </a>
          </div>
          <div className="support-social">
            <img
              src="/images/transparent.gif"
              title="Instagram"
              className="support-ig"
            />
            <a href="https://www.instagram.com/skyexchindia/" target="_blank">
              skyexchindia
            </a>
          </div>
        </div>
      </div>
      <div className="power-wrap power-wrap_forsky">
        <h3 id="powerWrapW" style={{ display: "none" }}>
          <span>Powered by</span>
          <img src="/images/transparent.gif" />
        </h3>
        <div className="licence_embed">
          <iframe
            src="https://licensing.gaming-curacao.com/validator/?lh=7a83475c9e54450a218a18bd28e33fad&template=seal"
            width={150}
            height={50}
            style={{ border: "none" }}
          />
        </div>
        <p>
          Skyexch.art is operated by Sky Infotech N.V. a limited liability
          company incorporated under the laws of Curacao with company
          Registration number 152377 with registered office at Abraham de
          Veerstraat 9 , Curacao P.O Box 3421 and is licensed and regulated by
          the Curacao authority as the regulatory body responsible holding a
          (Sub-license with License number 365/JAZ Sub-License GLH-
          OCCHKTW0707072017 granted on 6.07.2017).
          <br />
          Players are requested not to contact any untrusted sources for
          <a href="https://www.skyexch.art" target="_blank">
            https://www.skyexch.art/
          </a>
          accounts as this is an online site and they can only register
          independently without any agents. Only deposit through the account
          details generated by the system or provided by our official support
          team.
        </p>
        <div className="footer_info">
          <p className="icon_phone">
            <img src="/images/transparent.gif" />
            +351926917651 / +351926917279
          </p>
          <p>
            <a href="mailto:support@skyexch.art">
              <img src="/images/transparent.gif" />
              support@skyexch.art
            </a>
          </p>
        </div>
      </div>
      {/* Browser Support */}
      <div className="browser-wrap">
        <img src="/images/transparent.gif" />
        <br />
        Our website works best in the newest and last prior version of these
        browsers: <br />
        Google Chrome. Firefox
      </div>
      <ul className="policy-link">
        <li>
          <a>Privacy Policy</a>
        </li>
        <li>
          <a>Terms and Conditions</a>
        </li>
        <li>
          <a>Rules and Regulations</a>
        </li>
        <li>
          <a>KYC</a>
        </li>
        <li>
          <a>Responsible Gaming</a>
        </li>
        <li>
          <a>About Us</a>
        </li>
        <li>
          <a>Self-exclusion Policy</a>
        </li>
        <li>
          <a>Underage Policy</a>
        </li>
      </ul>
      <div className="app-link" style={{ display: "block" }}>
        <a>
          <img src="/images/btn-appdl.png" alt="" />
        </a>
        <p>v1.11 - 2022-03-23 - 3.1MB</p>
      </div>
    </div>
  );
};

export default Footer;
